name       : python-pymongo
version    : 4.2.0
release    : 10
source     :
    - https://github.com/mongodb/mongo-python-driver/archive/refs/tags/4.2.0.tar.gz : efd44e18a6f16156f8495d7786afbdc3952d1d09cfe9ad022bee3b86a6535e3f
license    : Apache-2.0
component  : programming.python
summary    : Python driver for MongoDB
description: |
    The PyMongo package contains tools for interacting with MongoDB database from Python:
    * bson: an implementation of the BSON format for Python.
    * pymongo: a native Python driver for MongoDB.
    * gridfs: a gridfs implementation on top of pymongo.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - mongodb
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
