name       : python-pymongo
version    : 3.9.0
release    : 4
source     :
    - https://github.com/mongodb/mongo-python-driver/archive/3.9.0.tar.gz : 1f471a6fb5465e2ebb91b6d9fb6922555996d55961bed08e999103f55634708c
license    :
    - Apache-2.0
component  : programming.python
summary    : Python driver for MongoDB
description: |
    The PyMongo package contains tools for interacting with MongoDB database from Python:
    * bson: an implementation of the BSON format for Python.
    * pymongo: a native Python driver for MongoDB.
    * gridfs: a gridfs implementation on top of pymongo.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - mongodb
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
