name       : python-pymongo
version    : 3.8.0
release    : 2
source     :
    - https://github.com/mongodb/mongo-python-driver/archive/3.8.0.tar.gz : 922659eac56131584de40d107cb0a98fa699bd2f80f9ff20b18c68c70aec5444
license    :
    - Apache-2.0
component  : programming.python
summary    : Python driver for MongoDB
description: |
    The PyMongo package contains tools for interacting with MongoDB database from Python:
    * bson: an implementation of the BSON format for Python.
    * pymongo: a native Python driver for MongoDB.
    * gridfs: a gridfs implementation on top of pymongo.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - mongodb
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test