name       : python-pymongo
version    : 4.1.1
release    : 9
source     :
    - https://github.com/mongodb/mongo-python-driver/archive/refs/tags/4.1.1.tar.gz : d85d46375f284e3d4640b642fb6389631e329bb9b071b69386feef331447c35b
license    : Apache-2.0
component  : programming.python
summary    : Python driver for MongoDB
description: |
    The PyMongo package contains tools for interacting with MongoDB database from Python:
    * bson: an implementation of the BSON format for Python.
    * pymongo: a native Python driver for MongoDB.
    * gridfs: a gridfs implementation on top of pymongo.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - mongodb
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
