name       : python-pymongo
version    : 3.11.4
release    : 6
source     :
    - https://github.com/mongodb/mongo-python-driver/archive/refs/tags/3.11.4.tar.gz : 5ccd7649a8e0acff61c0cdc1445fbc247205424df83ebc737e55c63fb9a0585c
license    :
    - Apache-2.0
component  : programming.python
summary    : Python driver for MongoDB
description: |
    The PyMongo package contains tools for interacting with MongoDB database from Python:
    * bson: an implementation of the BSON format for Python.
    * pymongo: a native Python driver for MongoDB.
    * gridfs: a gridfs implementation on top of pymongo.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - mongodb
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
